{"uuid":"6969406d-f2f9-449c-b3af-f064f60727f1","historyId":"49a6437471d6bcbe398243c6c591febf","fullName":"cloud.order.query.OrderFc.orderfc","labels":[{"name":"package","value":"cloud.order.query.OrderFc"},{"name":"testClass","value":"cloud.order.query.OrderFc"},{"name":"testMethod","value":"orderfc"},{"name":"parentSuite","value":"Suite_all"},{"name":"suite","value":"QueryOrderTest"},{"name":"subSuite","value":"cloud.order.query.OrderFc"},{"name":"host","value":"Administrator"},{"name":"thread","value":"121504@Administrator.TestNG-test=QueryOrderTest-6(17)"}],"links":[],"name":"订单反查","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.Throwable","trace":"java.lang.Throwable\r\n\tat message : 查询成功 expected [true] but found [false] in method : .orderfc(OrderFc:29)\r\n\tat cloud.order.query.OrderFc.orderfc(OrderFc.java:29)\r\n"},"stage":"finished","start":1589012135471,"stop":1589012139720,"parameters":[]}